### ISSUE TITLE
Menu's are bright red

### ISSUE THREAD

**Issue by Rob-DL** [breberafilip/snowflake-theme-vscode#1]
Using version 1.0.8 I get horrible looking bright red menus, including the context menu. See attached screenshot for example. I have not overrides in my workbench settings, other themes do correction colorize the menus.

![image](https://user-images.githubusercontent.com/3153796/82027514-a5d8da80-9694-11ea-9f3a-2c6bebafcb08.png)

**Comment by bxxf** [comment]
I am sorry for this experience, I wasn't able to test it because macOS vscode uses system context menus. Patch will be comming as soon as possible. Thank you for the feedback.

**Comment by bxxf** [comment]
It should be fixed by now. Contact me if you encounter any other issues.
